---
title: "Tutorial-3"
author: "Rahim Jutha"
date: "22/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Analysis my Spotify in R with spotifyr package
===
libraries and authorization 
```{r, warning=FALSE}
library(spotifyr)
library(tidyverse)
library(knitr)

Sys.setenv(SPOTIFY_CLIENT_ID = '6d7f3e6171c149a6b365504f76e3755c')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'c653ee4f4dc647668c44d5e8d4671091')

access_token <- get_spotify_access_token()
```

What's my favourite?
===
```{r}
if(!file.exists('raw_all_my_fav_tracks.rds')){
all_my_fav_tracks <-
  # This is somehow tough to read, but I lOVE PIPELINE!
  # FIRST we send get_my_saved_tracks request, set include_meta_info to TRUE, will return the number of all tracks in total. After that, we request 50 items per time, therefore, the looptime should be 50 divide the length of tracks.
  # Not all of us is lucky man, so if the number of tracks can't be divided exactly, we make one more time offset.
  ceiling(get_my_saved_tracks(include_meta_info = TRUE)[['total']] / 50) %>%
  # Generate a sequence by looptimes.
  seq() %>%
  # PlZ remember, the offset is start from zero, so we minus 1 from the offset. And everytime, we jump 50 items, because we have already request 50 items every time.
  # Every loop, we get a data.frame with 50 rows, once the loop finished, we got a list with looptime piece data.frame, with reduce(rbind), we can merge all the data.frames as one.
  map(function(x) {
    get_my_saved_tracks(limit = 50, offset = (x - 1) * 50)
  }) %>% reduce(rbind) %>%
  # For saving time, we can save the data as rds, this is not required, but it can take things back, once we make some mistakes.
  write_rds('raw_all_my_fav_tracks.rds')
# Let's check the structure of our tracks.
glimpse(all_my_fav_tracks)
}
```

Which music is my first love?
===
```{r}
if(file.exists('raw_all_my_fav_tracks.rds')){
  all_my_fav_tracks = readRDS("raw_all_my_fav_tracks.rds")
}

library(lubridate)
all_my_fav_tracks %>%
  mutate(added_at = ymd_hms(added_at)) %>%
  arrange(added_at) %>%
  head(1, wt = added_at) %>%
  select(track.name,added_at)  %>%
  kable()
```

Which Artists are my favourite
===
```{r}
artist_from_fav_tracks <-
  all_my_fav_tracks %>%
  select(track.artists) %>%
  reduce(rbind) %>%
  reduce(rbind) %>%
  # I don't think we need Urls in further analyses, id (unique mark of artist) and name are selected here.
  select(id, name)

track_num_artist <-
  artist_from_fav_tracks %>%
  count(id, sort = TRUE) %>%
  left_join(artist_from_fav_tracks, by = 'id',.) %>%
  unique() %>%
  select(-id) %>%
  top_n(20, n) %>%
  arrange(desc(n))

track_num_artist  %>%
  kable()
```

Visualizationn
===
```{r}
# For numerical variables, sometimes for simplifying problems, cut them into fractions is a good idea. Here, we go further, we fill the column plot with different color to represent different frequency group.
track_num_artist %>%
  mutate(
    freq = case_when(
      n > 50 ~ 'More than 50 tracks',
      between(n, 20, 49) ~ '20~49 tracks',
      TRUE ~ 'Less than 20 tracks'
    )
  ) %>%
  # To avoid mess up the order of frequency group, I always suggest to convert the category variables as factor variables, with built-in order, levels.
  mutate(freq = factor(
    freq,
    levels = c(
      'More than 50 tracks',
      '20~49 tracks',
      'Less than 20 tracks'
    )
  )) %>%
  ggplot(mapping = aes(
    x = reorder(name, -n),
    y = n,
    fill = freq
  )) +
  geom_col() +
  labs(fill = NULL,title = 'Who is My Favorite Artist',caption = 'data from spotify via spotiyr') +
  xlab('Artist') +
  ylab('Tracks Number') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = -60),
        axis.title = element_text(face = 'bold'),
        plot.title = element_text(hjust = 0.5, face = 'bold', size = 15),
        plot.caption = element_text(hjust = 1,face = 'bold.italic'))
```

Engery Valence Plot of my Top 20 Artists
===
```{r}
if(!file.exists('audio_features.rds')){
  track_num_artist$name %>%
    map(function(x){
      get_artist_audio_features(x)
      }) %>%
    reduce(rbind) %>%
    inner_join(all_my_fav_tracks,
               by = c('track_id' = 'track.id')) %>%
    write_rds('audio_features.rds')
}

audio_features <- read_rds('audio_features.rds')

ggplot(data = audio_features, aes(x = valence, y = energy, color = artist_name)) +
  geom_jitter() +
  geom_vline(xintercept = 0.5) +
  geom_hline(yintercept = 0.5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
  annotate('text', 0.25 / 2, 0.95, label = "Turbulent/Angry", fontface =
             "bold") +
  annotate('text', 1.75 / 2, 0.95, label = "Happy/Joyful", fontface = "bold") +
  annotate('text', 1.75 / 2, 0.05, label = "Chill/Peaceful", fontface =
             "bold") +
  annotate('text', 0.25 / 2, 0.05, label = "Sad/Depressing", fontface =
             "bold")
```
